version: "2"
services:
  master:
    image: jenkinsci/jenkins
    ports:
    - "80:8080"
    - "50000:50000"
#    environment:
#    - JAVA_OPTS=-Xmx2048m
    volumes:
    - ./jenkins-master:/var/jenkins_home
